# Generated by Django 4.0.5 on 2023-08-09 16:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wishes/%Y/%m/%d', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на продукт')),
                ('price', models.FloatField(verbose_name='Примерная цена')),
                ('public', models.BooleanField(default=True, verbose_name='Флаг публичности')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 20, 34, 4, 931610), verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('reason', models.CharField(blank=True, max_length=250, verbose_name='Повод')),
                ('done', models.BooleanField(default=False, verbose_name='Флаг выполнения')),
                ('deadline', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Срок')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
